version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/client
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/postinstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/appstart.sh
      runas: ec2-user
  ApplicationStop:
    - location: scripts/appstop.sh
      runas: ec2-user
