version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  pre_build:
    on-failure: ABORT
    commands:
      - "echo Installing dependencies..."
      - "npm --prefix client ci"
  build:
    commands:
      - "echo Running build..."
      - "npm --prefix client run build"
  post_build:
    commands:
      - "echo Moving appspec file"
      - "mv client/appspec.yml client/dist/ssr/"
      - "echo Moving scripts"
      - "mv client/scripts client/dist/ssr/"

artifacts:
  files:
    - '**/*'
  name: client-$(date +%Y-%m-%d)
  discard-paths: no
  base-directory: client/dist/ssr/

cache:
  paths:
    - './client/node_modules/**/*'
    - package-lock.json
