version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  pre_build:
    on-failure: ABORT
    commands:
      - "echo INSTALLING DEPENDENCIES..."
      - "npm --prefix client ci"
  build:
    commands:
      - "echo INSTALLING DEPENDENCIES..."
      - "npm --prefix client run build"

artifacts:
  files:
    - '**/*'
  name: client-$(date +%Y-%m-%d)
  discard-paths: no
  base-directory: client/dist/ssr/

cache:
  paths:
    - './client/node_modules/**/*'
    - package-lock.json
