name: dev
run-name: Dev workflow for ${{ github.ref_name }}
on:
  push:
    branches: [master]
jobs:
  filter_client_files:
    name: Filter Client Files
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: client/**
  push_changes:
    name: Push changes
    runs-on: ubuntu-latest
    needs: filter_client_files
    if: needs.filter_client_files.outputs.files_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-go/push@master
        with:
          ref: master
          remote-ref: dev
